### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by mazaaaa** [ultralytics/JSON2YOLO#50]
The Code just ran with no output.

**Comment by bcwein** [comment]
I am facing the same issue

I modified the main section to

`
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/json',  # directory with *.json
                          use_segments=True,
                          cls91to80=False)
`

And when i run the script

`
python general_json2yolo.py
`

It creates a new folder called **new_dir** with no contents.

**Comment by mazaaaa** [comment]
Hey, Bjorn, thanks for helping, that happened once i changed as you told but I'm not getting the converted file anywhere, please help.

**Comment by widedh** [comment]
hello, did you find a solution, please?

**Comment by SadeghPouriyanZadeh** [comment]
same here. it makes a new directory named "new_dir" and only create the directory structures in it. the problem is in this line:
https://github.com/ultralytics/JSON2YOLO/blob/c38a43f342428849c75c103c6d060012a83b5392/general_json2yolo.py#L306

`fn` is a PathPosix and so `f`. but the problem is that at last the `fn` directory is the result of `fn / f`.

What about the images directory in the created directory called `new_dir`?
There is no code to copy the source images to destination directory!

**Comment by glenn-jocher** [comment]
Thanks for reaching out! It appears that the issue might be occurring due to the usage of `fn / f` on the `PathPosix` objects `fn` and `f` at line 306, which may result in unexpected directory structure within `new_dir`. Additionally, there seems to be no code to copy the source images to the destination directory. These factors could be leading to the observed behavior. Let us know your thoughts on this.

**Comment by AJAY31797** [comment]
Same for me, the code is just creating an empty folder named 'new_dir' which contains two subfolders, 'images' and 'labels'. Both of these are empty. I have checked the values of the arguments use_segments and use_keypoints, both are correct as mentioned above. Could you suggest what could be the problem.

**Comment by ryouchinsa** [comment]
Hi @SadeghPouriyanZadeh, please copy images by yourself. Do you have any other problems?

Hi @AJAY31797, please show us your COCO JSON file. We can debug with the script.

**Comment by ponnyWu** [comment]
Find the section “Write”on line 308：
```
            # Write
            with open((fn / f).with_suffix(".txt"), "a") as file:
                for i in range(len(bboxes)):
                    line = (*(segments[i] if use_segments else bboxes[i]),)  # cls, box or segments
                    file.write(("%g " * len(line)).rstrip() % line + "\n")
```

Add two lines of code：
```
            # Write
            output_file_path = (fn / f).with_suffix(".txt")
            os.makedirs(os.path.dirname(output_file_path), exist_ok=True)

            with open((fn / f).with_suffix(".txt"), "a") as file:
                for i in range(len(bboxes)):
                    line = (*(segments[i] if use_segments else bboxes[i]),)  # cls, box or segments
                    file.write(("%g " * len(line)).rstrip() % line + "\n")
```

**Comment by glenn-jocher** [comment]
Hello @ponnyWu, thank you for your patience. It seems like you've identified a potential fix by ensuring the directory exists before attempting to write the file. This is a good catch! The `os.makedirs(os.path.dirname(output_file_path), exist_ok=True)` line creates the directory structure needed for the output file if it doesn't already exist. This should resolve the issue of the script creating empty folders. If you continue to experience problems, please provide a snippet of your COCO JSON file for further debugging. Your contributions are valuable to the community! 🌟

**Comment by joaoparaujo01** [comment]
Hello, I add the two lines mentioned before but still getting empty folders.
I annotated an image with keypoints using a skeleton.
This is the content of my annotations.json:
`{"licenses":[{"name":"","id":0,"url":""}],"info":{"contributor":"","date_created":"","description":"","url":"","version":"","year":""},"categories":[{"id":1,"name":"large_box","supercategory":"","keypoints":["1","2","3","4","5","6","7","8"],"skeleton":[[1,2],[3,4],[1,5],[3,7],[2,3],[6,7],[2,6],[5,6],[4,8],[4,1],[8,5],[7,8]]},{"id":10,"name":"small_box","supercategory":"","keypoints":["1","2","3","4","5","6","7","8"],"skeleton":[[1,2],[3,4],[1,5],[3,7],[2,3],[6,7],[2,6],[5,6],[4,8],[4,1],[8,5],[7,8]]}],"images":[{"id":1,"width":1920,"height":1080,"file_name":"IMG_23.jpg","license":0,"flickr_url":"","coco_url":"","date_captured":0}],"annotations":[{"id":1,"image_id":1,"category_id":1,"segmentation":[],"area":205848.79199999996,"bbox":[935.85,399.0,611.19,336.8],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[935.85,414.18,2,943.25,563.55,2,1547.04,543.32,2,1393.33,399.0,2,941.1,573.14,2,951.89,735.8,2,1494.75,712.15,2,1391.7,558.72,2],"num_keypoints":8}]}`

Maybe is something missing on JSON file but I'm new using annotations tools and can't figure it out
Thanks in advance

**Comment by glenn-jocher** [comment]
Thanks @mazaaaa and everyone who reported empty new_dir output. PR #129 has been merged with explicit --save-dir support, a clear error when no JSON files are found, safer nested label writing, and tests covering the output path behavior.
